# Generated by Django 5.1 on 2026-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('leafy', 'Leafy Green (e.g. Spinach, Ugwu)'), ('fruit', 'Fruiting Vegetable (e.g. Tomato, Pepper, Cucumber)'), ('root', 'Root & Tuber (e.g. Carrot, Sweet Potato)'), ('bulb', 'Bulb (e.g. Onion, Garlic)'), ('legume', 'Legume (e.g. Green Beans, Cowpea)'), ('other', 'Other')], default='fruit', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('growing_duration_days', models.PositiveIntegerField(default=60, help_text='Average days from planting to harvest')),
                ('ideal_temperature', models.CharField(blank=True, help_text='e.g. 20°C - 30°C', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('problem_type', models.CharField(choices=[('disease', 'Disease (Fungal/Bacterial/Viral)'), ('pest', 'Pest / Insect Infestation'), ('deficiency', 'Nutrient Deficiency')], default='disease', max_length=20)),
                ('causal_agent', models.CharField(blank=True, help_text='e.g. Alternaria solani, Bemisia tabaci', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Moderate'), ('high', 'High / Severe')], default='medium', max_length=10)),
                ('symptoms', models.TextField(help_text='Key visible symptoms on leaves, stems, or fruits')),
                ('organic_treatment', models.TextField(blank=True, help_text='Eco-friendly / cultural / organic control methods')),
                ('chemical_treatment', models.TextField(blank=True, help_text='Recommended chemical fungicides/pesticides if severe')),
                ('prevention_tips', models.TextField(blank=True, help_text='Crop rotation, spacing, resistant varieties')),
                ('image_url', models.URLField(blank=True, help_text='Optional reference image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_vegetables', models.ManyToManyField(related_name='pests_and_diseases', to='vegeviewapp.vegetable')),
            ],
            options={
                'verbose_name': 'Pest & Disease',
                'verbose_name_plural': 'Pests & Diseases',
                'ordering': ['name'],
            },
        ),
    ]
