# Generated by Django 5.1 on 2024-09-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegeviewapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
