# Generated by Django 5.1 on 2024-09-23 11:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegeviewapp', '0002_rename_dob_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
