# Generated by Django 5.1 on 2024-09-23 12:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegeviewapp', '0003_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1230123456789', max_length=128, region=None),
        ),
    ]
